config/routes.rb
Rails.application.routes.draw do
  get '/admin', to: 'admin#index'
  get '/admin/new', to: 'admin#new'
  post '/create_user', to: 'admin#create_user'
  
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get '/admin/trader_list', to: 'admin#trader_list'
  get '/admin/trader_details/:id', to: 'admin#trader_details'
  get '/admin/trader/:id/edit', to: 'admin#edit_trader'
  put '/admin/trader_list', to: 'admin#update_trader'


  resources :traders


  default_url_options :host => 'localhost'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/price_service.rb
class PriceService
    def self.fetch_prices(ticker)
        timeseries = client.
        stock(symbol: ticker)
        .timeseries(adjusted: true, outputsize: 'full')
        .output["Time Series (Daily)"]
        .map{ |k, v\}
    end

    def self.client
        @client ||= Alphavantage::Client.new( key: "OOSGWQH54M1W1WJL")
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable

  def active_for_authentication? 
    super && approved?
  end 
  
  def inactive_message 
    approved? ? super : :not_approved
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:approved] == "false"
      @users = User.where(approved: false)
    else
      @users = User.all
    end
  end
  
  def create_user
    flash.now[:notice] = "save"
    @user = User.new(params.permit(:email, :password))
      @user.user_type = 'trader'
      if @user.save!
        flash.now[:notice] = "save"
        redirect_to root_path
      else
        flash.now[:notice] = "not save"
        render admin_new_path
      end
  end

  def trader_list
    @users = User.where.not(user_type: 'admin')
    render 'users/index'
  end

  def trader_details
    @user = User.find(params[:id])
    render 'users/show'
  end

  def edit_trader
    @user = User.find(params[:id])
    render 'users/edit'
  end

  def update_trader
    @user = User.find(params[:user][:id])
    if @user.update(user_params)
      redirect_to "/admin/trader_list"
    else
      render 'users/edit'
    end
  end

  private
  def user_params
      params.require(:user).permit(:email, :id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/traders_controller.rb
class TradersController < ApplicationController
    before_action :authenticate_user!

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])

      if @user.update(user_params)
        redirect_to user_path
      else
        render :edit
      end
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      @user.user_type = 'trader'
      debugger
      if @user.save!

        redirect_to root_path
      else
        render admin_new_path
      end
    end

    private
    def user_params
        params.require(:user).permit(:email, :id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin</h1>

<%= button_to 'Create User', admin_new_path, data:{ turbo:false }, method: :get %>
<%= button_to 'See All Traders', admin_trader_list_path, data:{ turbo:false }, method: :get %>

<table>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %>
      <td><%= user.approved %>
    </tr>
  <% end %>
</table>

app/views/admin/new.html.erb
<h1>Create</h1>

<%= form_with model: @user, url: '/create_user', method: :post do |form| %>
  <%= form.email_field :email, placeholder: "Email" %>
  <%= form.password_field :password, placeholder: "Password" %>

  <%= form.submit 'Create user' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TradingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_for @user, url: admin_trader_list_path, local: true, method: :put do |f| %>

    <p>
      <% if @user.errors.any? %>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>      
        </ul>
      <% end %>
    </p>
    
    <p>
      <%= f.label :email %><br/>
      <%= f.text_field :email %>
      <%= f.hidden_field :id, value: @user.id %>
    </p>
    
    <p>
      <%= f.submit %>
    </p>
    
    <% end %>

app/views/users/index.html.erb
<h1>List of All Traders</h1>

<% @users.each do |user| %>
  <%= user.id %>
  <%= user.email %>
  <%= link_to 'Show', "/admin/trader_details/#{user.id}" %>
  <br/>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= @user.id %>
<%= @user.email %>
<%= link_to 'Edit', "/admin/trader/#{@user.id}/edit" %>